modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"
[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="Torchflower Arrows"
logoFile="mod.png"
authors="${mod_authors}"

description='''
If a cave is too dark to explore, simply shoot a torchflower into the darkness to light your path.
'''

[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"
